Add mocks to NodeJS "timers" module
sinonjs/lolex pull request #467
Opened 2023-05-16 09:16 UTC by swenzel-arc

#### Purpose (TL;DR) - mandatory

Fix issue #466 

#### Solution
It works like this:

Try to import `timers` module as `timersModule`. If it doesn't work, that's okay.

Upon `FakeTimers.install()`, iff we're installing on the `globalObject` and `timersModule` was successfully imported:
For each property that was mocked on the globalObject iff it also exists on `timersModule`:
Safe its name and original value from `timersModule` to a new property on the Clock object.
Then set it to the same property as the faked property on `globalObject`.

Upon `FakeTimers.uninstall()`, iff the object holding `timersModule`'s originals is truthy:
For each entry set the corresponding property back to the original.

2023-05-16 13:49 UTC, fatso83 requested changes
I think you could probably afford adding a line to the README that we touch the `"timers"` module, but otherwise this generally looks fine! Just a few minor things.

2023-05-16 13:49 UTC, fatso83 commented on test/issue-466-test.js
> +"use strict";
Stuff the tests inside of this into a suitably named new describe block in `fake-timers-test.js`. We usually reserve the `issues*` files for regression test cases.

2023-05-16 13:49 UTC, fatso83 commented on test/issue-466-test.js
> +}
Just use Mocha's built-ins to selectively run it in supported environments
```javascript
        before(function () {
            if (!timersModule) {
                this.skip();
            }
        });
```
Enables a bit better reporting :)

2023-05-16 13:49 UTC, fatso83 commented on src/fake-timers-src.js
> +            if (clock.timersModuleMocks) {
They are not [actual mocks](https://www.martinfowler.com/articles/mocksArentStubs.html), though, so could trim that bit off.

To be consistent with the `methods` prop, just name it `timersModuleMethods`

2023-05-16 16:58 UTC, benjamingr commented
> Btw. do you think we should add a config flag that allows to skip altering the timers module?

No but that's a good point, it should respect the regular "should I mock setTimeout/setInterval or whatever" option (toFake)

2023-05-18 13:36 UTC, fatso83 approved these changes

2023-05-18 13:37 UTC, merged

2023-05-18 13:40 UTC, fatso83 commented
Out as 10.2.0

2023-06-12 12:03 UTC, fatso83 commented
Seems like #470 made a good candidate for why this could have been behind a flag. Some weird regression hitting us.